services:
  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./api/app:/app/app
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
    networks:
      - ticket-analyzer-net

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ticket-analyzer-net

volumes:
  ollama_data:

networks:
  ticket-analyzer-net:
